doc: add development setup document
QOSQOs/UNIVeasier pull request #24
Opened 2019-10-16 20:35 UTC by Kleiber

2019-10-17 02:31 UTC, darwinTtito requested changes
Start all the phrases with a verb.

2019-10-17 02:31 UTC, darwinTtito commented on docs/devSetup.md
> +In order to run the unit test. To run an especific test, go to the folder where the file containing the tests is located and run:
The first part does not have sense.

2019-10-17 03:45 UTC, PDFAtauchi commented on docs/devSetup.md
> +$ cd $REPO/../UNIVeasier-ui
add `npm install`

2019-10-18 01:04 UTC, darwinTtito approved these changes

2019-10-18 01:05 UTC, merged